# Permalinks
#permalink:           pretty
permalink:           :title

# Setup
title:               notes from userspace
tagline:             ''
description:         ''
url:                 https://jmeosbn.github.io/lanyon
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Jamie Osborne
  url:               https://twitter.com/jmeosbn
  email:             


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed



# Custom vars
version:             1.0.0
